// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myapi.Data;

#nullable disable

namespace myapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240723235826_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myshared.Models.PortfolioProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alot of fun",
                            Title = "First project",
                            WebUrl = "google.dk"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Alot of fun",
                            Title = "Second project",
                            WebUrl = "google.dk"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Alot of fun",
                            Title = "Third project",
                            WebUrl = "google.dk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
