// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myapi.Data;

#nullable disable

namespace myapi.Migrations
{
    [DbContext(typeof(MssqlDataContext))]
    [Migration("20250215162516_removeWebUrl")]
    partial class removeWebUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myshared.Models.ExampleModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExampleModels");

                    b.HasData(
                        new
                        {
                            Id = "67b0bfec0521f6c22218c93b",
                            Description = "Some field of first example",
                            Title = "First example"
                        },
                        new
                        {
                            Id = "67b0bfec0521f6c22218c93d",
                            Description = "Some field of second example",
                            Title = "Second example"
                        },
                        new
                        {
                            Id = "67b0bfec0521f6c22218c93f",
                            Description = "Some field of third example",
                            Title = "Third example"
                        });
                });

            modelBuilder.Entity("myshared.Models.ExampleNavigationProperty", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExampleModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExampleModelId");

                    b.ToTable("ExampleNavigationProperties");

                    b.HasData(
                        new
                        {
                            Id = "67b0bfec0521f6c22218c940",
                            ExampleModelId = "67b0bfec0521f6c22218c93b",
                            Title = "First navprop"
                        },
                        new
                        {
                            Id = "67b0bfec0521f6c22218c941",
                            ExampleModelId = "67b0bfec0521f6c22218c93b",
                            Title = "Second navprop"
                        },
                        new
                        {
                            Id = "67b0bfec0521f6c22218c942",
                            ExampleModelId = "67b0bfec0521f6c22218c93d",
                            Title = "Third navprop"
                        });
                });

            modelBuilder.Entity("myshared.Models.ExampleNavigationProperty", b =>
                {
                    b.HasOne("myshared.Models.ExampleModel", "ExampleModel")
                        .WithMany("ExampleNavigationProperty")
                        .HasForeignKey("ExampleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleModel");
                });

            modelBuilder.Entity("myshared.Models.ExampleModel", b =>
                {
                    b.Navigation("ExampleNavigationProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
