// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myapi.Data;

#nullable disable

namespace myapi.Migrations
{
    [DbContext(typeof(MssqlDataContext))]
    partial class MssqlDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myshared.Models.ExampleModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExampleModels");

                    b.HasData(
                        new
                        {
                            Id = "672c3df356274e2164c88fa4",
                            Description = "Alot of fun",
                            Title = "First project",
                            WebUrl = "google.dk"
                        },
                        new
                        {
                            Id = "672c3df356274e2164c88fa5",
                            Description = "Alot of fun",
                            Title = "Second project",
                            WebUrl = "google.dk"
                        },
                        new
                        {
                            Id = "672c3df356274e2164c88fa6",
                            Description = "Alot of fun",
                            Title = "Third project",
                            WebUrl = "google.dk"
                        });
                });

            modelBuilder.Entity("myshared.Models.ExampleNavigationProperty", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExampleModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExampleModelId");

                    b.ToTable("ExampleNavigationProperties");

                    b.HasData(
                        new
                        {
                            Id = "672c3df356274e2164c88fa7",
                            ExampleModelId = "672c3df356274e2164c88fa4",
                            Title = "First navprop"
                        },
                        new
                        {
                            Id = "672c3df356274e2164c88fa8",
                            ExampleModelId = "672c3df356274e2164c88fa4",
                            Title = "Second navprop"
                        },
                        new
                        {
                            Id = "672c3df356274e2164c88fa9",
                            ExampleModelId = "672c3df356274e2164c88fa5",
                            Title = "Third navprop"
                        });
                });

            modelBuilder.Entity("myshared.Models.ExampleNavigationProperty", b =>
                {
                    b.HasOne("myshared.Models.ExampleModel", "ExampleModel")
                        .WithMany("ExampleNavigationProperty")
                        .HasForeignKey("ExampleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleModel");
                });

            modelBuilder.Entity("myshared.Models.ExampleModel", b =>
                {
                    b.Navigation("ExampleNavigationProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
