services:
  mongo:
    container_name: mongo-server
    image: 'mongo:latest'
    ports:
      - "13337:27017"
    volumes:
      - ./entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # use to mount script mongo-init.js script that runs on build
      - mongodata:/data/db
    environment:
            MONGO_INITDB_ROOT_USERNAME: sa
            MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
            MONGO_INITDB_DATABASE: mydb

  sql:
    container_name: mssql-server
    image: 'mcr.microsoft.com/mssql/server:latest'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    user: root
    ports:
      - "12345:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
    volumes:
     - ./entrypoint:/entrypoint # use to mount scripts to a folder in container
     - mssqldata:/var/opt/mssql/data
    entrypoint: # use to run scripts after building
      - ./entrypoint/sql-entrypoint.sh

volumes:
  mssqldata:
  mongodata: