name: SyncDB

on:
  push:
    branches:
      - fullstack
  workflow_dispatch:

jobs:
  syncdb:
      runs-on: windows-latest
      
      steps:
        - uses: actions/checkout@v4
  
        - name: Install EF Core CLI
          run: dotnet tool install dotnet-ef --global
          shell: bash
        
        - name: Update db
          uses: nick-fields/retry@v3
          with:
            timeout_minutes: 2
            max_attempts: 5
            command: | 
              cd 'D:\a\mydotnet\mydotnet\myapi\'
              dotnet ef database update --connection '${{ secrets.CONNECTIONSTRING }}'
